# Site settings
title: Type Test
version: "v1"
description: "Stop writing CSS and start building prototypes."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://labs.edouard.us/type-test/" # the base hostname & protocol for your site
twitter_username: joshosbrn
github_username:  joshosbrn

# Build settings
markdown: kramdown

exclude: [node_modules, gulpfile.js]

# Jekyll Get

jekyll_get:
  data: team
  json: 'https://18f.gsa.gov/hub/api/team/'
